# Generated by Django 4.2 on 2024-01-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='fk_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.suppliermodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='fk_user_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useremployeemodel'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='fk_user_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useremployeemodel'),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='fk_user_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useremployeemodel'),
        ),
    ]
