# Generated by Django 4.2 on 2024-01-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brandmodel',
            table='APIS_BRAND',
        ),
        migrations.AlterModelTable(
            name='categorymodel',
            table='APIS_CATEGORY',
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table='APIS_PRODUCT',
        ),
    ]
