# Generated by Django 5.0.1 on 2024-02-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnCheckModel',
            fields=[
                ('own_check_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('own_check_payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('own_check_beneficiary', models.CharField(max_length=500, verbose_name='Beneficiario')),
                ('own_check_detail', models.CharField(max_length=500, verbose_name='Detalle')),
                ('own_check_voucher_type', models.CharField(max_length=50, verbose_name='Tipo de Comprobante')),
                ('own_check_voucher_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de Comprobante')),
                ('own_check_deposit_date', models.DateField(verbose_name='Fecha de Deposito')),
                ('own_check_bank', models.CharField(max_length=256, verbose_name='Banco')),
                ('own_check_account_number', models.CharField(max_length=256, verbose_name='Numero de Cuenta')),
                ('own_check_number', models.CharField(max_length=100, verbose_name='Cheque Numero')),
                ('own_check_owner', models.CharField(max_length=256, verbose_name='Propietario')),
                ('own_check_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Monto')),
                ('own_check_status', models.CharField(max_length=50, verbose_name='Estado')),
                ('own_check_remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('own_check_create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('own_check_upgrade_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'CHEQUE PROPIO',
                'verbose_name_plural': 'CHEQUES PROPIOS',
                'db_table': 'APIS_OWN_CHECK',
            },
        ),
    ]
