# Generated by Django 5.0.1 on 2024-01-23 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeModel',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('income_voucher_type', models.CharField(max_length=256, verbose_name='Tipo de Comprobate')),
                ('income_voucher_number', models.CharField(max_length=100, verbose_name='Numero de Comprobante')),
                ('income_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('income_tax_percentage', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Porcentaje IVA')),
                ('income_tax', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='IVA')),
                ('income_total', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total')),
                ('income_status', models.CharField(max_length=50, verbose_name='Estado')),
                ('income_status_description', models.CharField(default='Ninguno', max_length=256, verbose_name='Descripción')),
                ('income_create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'INGRESO',
                'verbose_name_plural': 'INGRESOS',
                'db_table': 'APIS_INCOME',
            },
        ),
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('document_type', models.CharField(max_length=20, verbose_name='Tipo de Documento')),
                ('document_number', models.PositiveIntegerField(verbose_name='Numero')),
                ('lastname', models.CharField(max_length=500, verbose_name='Apellidos')),
                ('name', models.CharField(max_length=500, verbose_name='Nombres')),
                ('country', models.CharField(max_length=200, verbose_name='Pais')),
                ('state_province', models.CharField(max_length=200, verbose_name='Provincia o Estado')),
                ('city', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('postal_code', models.CharField(default='S/N', max_length=200, verbose_name='Codigo Postal')),
                ('phone_number', models.CharField(default='Sin Telefono Convencional', max_length=50, verbose_name='Telefono')),
                ('cellphone_number', models.CharField(max_length=50, verbose_name='Celular')),
                ('email', models.CharField(default='No Posee email', max_length=100, verbose_name='E-mail')),
                ('client_img', models.CharField(max_length=500, verbose_name='Imagen')),
                ('supplier_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=50, verbose_name='Codigo de Proveedor')),
                ('supplier_tradename', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre Comercial')),
                ('supplier_branch_office_address_one', models.CharField(default='Sin Sucursal', max_length=200, verbose_name='Dirección')),
                ('supplier_branch_office_address_two', models.CharField(default='Sin Sucursal', max_length=200, verbose_name='Dirección')),
                ('supplier_branch_office_address_three', models.CharField(default='Sin Sucursal', max_length=200, verbose_name='Dirección')),
                ('supplier_branch_office_address_four', models.CharField(default='Sin Sucursal', max_length=200, verbose_name='Dirección')),
                ('supplier_phone_number_one', models.CharField(default='No posee numero telefonico', max_length=50, verbose_name='Telefono')),
                ('supplier_phone_number_two', models.CharField(default='No posee numero telefonico', max_length=50, verbose_name='Telefono')),
                ('supplier_phone_number_three', models.CharField(default='No posee numero telefonico', max_length=50, verbose_name='Telefono')),
                ('supplier_phone_number_four', models.CharField(default='No posee numero telefonico', max_length=50, verbose_name='Telefono')),
                ('supplier_status', models.CharField(max_length=50, verbose_name='Estado')),
                ('supplier_status_description', models.CharField(default='Ninguna', max_length=256, verbose_name='Descripción')),
                ('supplier_create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('supplier_upgrade_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'PROVEEDOR',
                'verbose_name_plural': 'PROVEEDORES',
                'db_table': 'APIS_SUPPLIER',
            },
        ),
        migrations.CreateModel(
            name='IncomeDetailModel',
            fields=[
                ('income_detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('income_detail_quantity', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Cantidad')),
                ('income_detail_purchase_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio de Compra')),
                ('income_detail_sale_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio de Venta')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'DETALLE DE INGRESO',
                'verbose_name_plural': 'DETALLES DE INGRESO',
                'db_table': 'APIS_INCOME_DETAIL',
            },
        ),
    ]
