# Generated by Django 4.2 on 2024-01-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incomedetailmodel',
            table='APIS_INCOME_DETAIL',
        ),
        migrations.AlterModelTable(
            name='incomemodel',
            table='APIS_INCOME',
        ),
        migrations.AlterModelTable(
            name='suppliermodel',
            table='APIS_SUPPLIER',
        ),
    ]
