# Generated by Django 5.0.2 on 2024-04-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Codigo de Marca')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(default='Ninguna', max_length=256, verbose_name='Descripción')),
                ('img', models.CharField(max_length=256, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'MARCA',
                'verbose_name_plural': 'MARCAS',
                'db_table': 'APIS_BRAND',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Codigo de Categoria')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(default='Ninguna', max_length=256, verbose_name='Descripción')),
                ('img', models.CharField(max_length=256, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'CATEGORIA',
                'verbose_name_plural': 'CATEGORIAS',
                'db_table': 'APIS_CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default='No posee codigo', max_length=13, verbose_name='Codigo de Barras')),
                ('code', models.CharField(max_length=50, verbose_name='Codigo de Producto')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('stock', models.PositiveBigIntegerField(verbose_name='Stock')),
                ('presentation', models.CharField(max_length=256, verbose_name='Presentación')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio de Compra')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio de Venta')),
                ('number_sale', models.PositiveBigIntegerField(default=0, verbose_name='Numero de Ventas')),
                ('img', models.CharField(max_length=256, verbose_name='Imagen')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('description', models.CharField(default='Ninguna', max_length=256, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'PRODUCTO',
                'verbose_name_plural': 'PRODUCTOS',
                'db_table': 'APIS_PRODUCT',
            },
        ),
    ]
