# Generated by Django 4.2 on 2024-01-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashregisters', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cashregisterclosingmodel',
            table='APIS_CASH_REGISTER_CLOSING',
        ),
        migrations.AlterModelTable(
            name='cashregistermodel',
            table='APIS_CASH_REGISTER',
        ),
        migrations.AlterModelTable(
            name='cashregistermovementsmodel',
            table='APIS_CASH_REGISTER_MOVEMENTS',
        ),
        migrations.AlterModelTable(
            name='cashregisteropeningmodel',
            table='APIS_CASH_REGISTER_OPENING',
        ),
    ]
