# Generated by Django 5.0.2 on 2024-04-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('document_type', models.CharField(max_length=20, verbose_name='Tipo de Documento')),
                ('document_number', models.PositiveIntegerField(verbose_name='Numero')),
                ('lastname', models.CharField(max_length=500, verbose_name='Apellidos')),
                ('name', models.CharField(max_length=500, verbose_name='Nombres')),
                ('country', models.CharField(max_length=200, verbose_name='Pais')),
                ('state_province', models.CharField(max_length=200, verbose_name='Provincia o Estado')),
                ('city', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('postal_code', models.CharField(default='S/N', max_length=200, verbose_name='Codigo Postal')),
                ('phone_number', models.CharField(default='Sin Telefono Convencional', max_length=50, verbose_name='Telefono')),
                ('cellphone_number', models.CharField(max_length=50, verbose_name='Celular')),
                ('email', models.CharField(default='No Posee email', max_length=100, verbose_name='E-mail')),
                ('img', models.ImageField(blank=True, null=True, upload_to='persons/', verbose_name='Imagen')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Codigo de Empleado')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('contract_type', models.CharField(default='No posee contrato', max_length=256, verbose_name='Tipo de Contrato')),
                ('contract_code', models.CharField(default='No posee codigo', max_length=256, verbose_name='Codigo de Contrato')),
                ('admission_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('departament', models.CharField(max_length=256, verbose_name='Area o Departamento')),
                ('position', models.CharField(max_length=256, verbose_name='Cargo')),
                ('extension_number', models.CharField(default='No Posee Extensión', max_length=50, verbose_name='Numero de Extensión')),
            ],
            options={
                'verbose_name': 'EMPLEADO',
                'verbose_name_plural': 'EMPLEADOS',
                'db_table': 'APIS_EMPLOYEE',
            },
        ),
    ]
