# Generated by Django 5.0.2 on 2024-04-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCheckModel',
            fields=[
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admission', models.DateField(verbose_name='Fecha de Admisión')),
                ('detail', models.CharField(max_length=500, verbose_name='Detalle')),
                ('voucher_type', models.CharField(max_length=256, verbose_name='Tipo de Comprobante')),
                ('voucher_number', models.CharField(max_length=100, verbose_name='Numero del Comprobante')),
                ('deposit_date', models.DateField(verbose_name='Fecha de Deposito')),
                ('bank', models.CharField(max_length=256, verbose_name='Banco')),
                ('account_number', models.CharField(max_length=256, verbose_name='Numero de Cuenta')),
                ('check_number', models.CharField(max_length=100, verbose_name='Numero de Cheque')),
                ('owner', models.CharField(max_length=256, verbose_name='Propietario de la Cuenta')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Monto')),
                ('status', models.CharField(max_length=50, verbose_name='Estado')),
                ('deposited_in', models.CharField(blank=True, max_length=256, null=True, verbose_name='Depositado en Banco')),
                ('deposit_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Comprobante')),
                ('endorsement_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Endoso')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Descargo')),
                ('beneficiary', models.CharField(blank=True, max_length=500, null=True, verbose_name='Beneficiario')),
                ('remark', models.CharField(default='Ninguna', max_length=500, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'CHEQUE DEL CLIENTE',
                'verbose_name_plural': 'CHEQUES DEL CLIENTE',
                'db_table': 'APIS_CLIENT_CHECK',
            },
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Codigo de Cliente')),
                ('name', models.CharField(max_length=500, verbose_name='Appelidos y Nombre')),
                ('trade_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre Comercial')),
                ('branch_office_address_one', models.CharField(default='Sin Sucursal', max_length=200, verbose_name='Dirección')),
                ('branch_office_address_two', models.CharField(default='Sin Sucursal', max_length=200, verbose_name='Dirección')),
                ('branch_office_address_three', models.CharField(default='Sin Sucursal', max_length=200, verbose_name='Dirección')),
                ('branch_office_address_four', models.CharField(default='Sin Sucursal', max_length=200, verbose_name='Dirección')),
                ('phone_number_one', models.CharField(default='No posee numero telefonico', max_length=50, verbose_name='Telefono')),
                ('phone_number_two', models.CharField(default='No posee numero telefonico', max_length=50, verbose_name='Telefono')),
                ('phone_number_three', models.CharField(default='No posee numero telefonico', max_length=50, verbose_name='Telefono')),
                ('phone_number_four', models.CharField(default='No posee numero telefonico', max_length=50, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'CLIENTE',
                'verbose_name_plural': 'CLIENTES',
                'db_table': 'APIS_CLIENT',
            },
        ),
    ]
