# Generated by Django 4.2 on 2024-01-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='owncheckmodel',
            table='APIS_OWN_CHECK',
        ),
    ]
