# Generated by Django 4.2 on 2024-01-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='fk_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientmodel'),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='fk_sale_voucher_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.vouchertypemodel'),
        ),
    ]
