# Generated by Django 5.0.1 on 2024-01-09 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_initial'),
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotemodel',
            name='fk_user_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnotedetailmodel',
            name='fk_credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.creditnotemodel'),
        ),
        migrations.AddField(
            model_name='saledetailmodel',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel'),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='fk_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientmodel'),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='fk_user_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saledetailmodel',
            name='fk_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.salemodel'),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='fk_sale_voucher_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.vouchertypemodel'),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='fk_way_to_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.waytopaymodel'),
        ),
    ]
