# Generated by Django 4.2 on 2024-01-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0003_initial'),
        ('clients', '0002_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetailmodel',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel'),
        ),
        migrations.AddField(
            model_name='saledetailmodel',
            name='fk_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.salemodel'),
        ),
        migrations.AddField(
            model_name='creditnotemodel',
            name='fk_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientmodel'),
        ),
        migrations.AddField(
            model_name='creditnotemodel',
            name='fk_user_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useremployeemodel'),
        ),
        migrations.AddField(
            model_name='creditnotedetailmodel',
            name='fk_credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.creditnotemodel'),
        ),
        migrations.AddField(
            model_name='creditnotedetailmodel',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel'),
        ),
    ]
