# Generated by Django 4.2 on 2024-01-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='creditnotedetailmodel',
            table='APIS_CREDIT_NOTE_DETAIL',
        ),
        migrations.AlterModelTable(
            name='creditnotemodel',
            table='APIS_CREDIT_NOTE',
        ),
        migrations.AlterModelTable(
            name='saledetailmodel',
            table='APIS_SALE_DETAIL',
        ),
        migrations.AlterModelTable(
            name='salemodel',
            table='APIS_SALE',
        ),
        migrations.AlterModelTable(
            name='vouchertypemodel',
            table='APIS_VOUCHER_TYPE',
        ),
        migrations.AlterModelTable(
            name='waytopaymodel',
            table='APIS_WAY_TO_PAY',
        ),
    ]
