# Generated by Django 5.0.2 on 2024-04-08 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(max_length=256, verbose_name='Tipo de Comprobate')),
                ('voucher_number', models.CharField(max_length=100, verbose_name='Numero de Comprobante')),
                ('income_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Porcentaje IVA')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'INGRESO',
                'verbose_name_plural': 'INGRESOS',
                'db_table': 'APIS_INCOME',
            },
        ),
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('document_type', models.CharField(max_length=20, verbose_name='Tipo de Documento')),
                ('document_number', models.PositiveIntegerField(verbose_name='Numero')),
                ('country', models.CharField(max_length=200, verbose_name='Pais')),
                ('state_province', models.CharField(max_length=200, verbose_name='Provincia o Estado')),
                ('city', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('postal_code', models.CharField(default='S/N', max_length=200, verbose_name='Codigo Postal')),
                ('phone_number', models.CharField(default='Sin Telefono Convencional', max_length=50, verbose_name='Telefono')),
                ('cellphone_number', models.CharField(max_length=50, verbose_name='Celular')),
                ('email', models.CharField(default='No Posee email', max_length=100, verbose_name='E-mail')),
                ('img', models.ImageField(blank=True, null=True, upload_to='persons/', verbose_name='Imagen')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Codigo de Proveedor')),
                ('business_name', models.CharField(max_length=500, verbose_name='Razon Social')),
                ('tradename', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre Comercial')),
                ('branch_office_address_one', models.CharField(default='Sin Sucursal', max_length=200, verbose_name='Dirección')),
                ('branch_office_address_two', models.CharField(default='Sin Sucursal', max_length=200, verbose_name='Dirección')),
                ('branch_office_address_three', models.CharField(default='Sin Sucursal', max_length=200, verbose_name='Dirección')),
                ('branch_office_address_four', models.CharField(default='Sin Sucursal', max_length=200, verbose_name='Dirección')),
                ('phone_number_one', models.CharField(default='No posee numero telefonico', max_length=50, verbose_name='Telefono')),
                ('phone_number_two', models.CharField(default='No posee numero telefonico', max_length=50, verbose_name='Telefono')),
                ('phone_number_three', models.CharField(default='No posee numero telefonico', max_length=50, verbose_name='Telefono')),
                ('phone_number_four', models.CharField(default='No posee numero telefonico', max_length=50, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'PROVEEDOR',
                'verbose_name_plural': 'PROVEEDORES',
                'db_table': 'APIS_SUPPLIER',
            },
        ),
        migrations.CreateModel(
            name='IncomeDetailModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Cantidad')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio de Compra')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio de Venta')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'DETALLE DE INGRESO',
                'verbose_name_plural': 'DETALLES DE INGRESO',
                'db_table': 'APIS_INCOME_DETAIL',
            },
        ),
    ]
