# Generated by Django 5.0.2 on 2024-04-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermodel',
            name='document_number',
            field=models.CharField(max_length=20, verbose_name='Numero'),
        ),
    ]
