# Generated by Django 4.2.1 on 2023-09-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdminWeb',
            fields=[
                ('user_admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_admin_name', models.CharField(max_length=256)),
                ('user_admin_lastname', models.CharField(max_length=256)),
                ('user_admin_user_name', models.CharField(max_length=256)),
                ('user_client_password', models.CharField(max_length=16)),
                ('user_client_login', models.IntegerField()),
                ('user_client_status', models.IntegerField()),
                ('user_client_status_description', models.CharField(blank=True, max_length=256, null=True)),
                ('user_client_create_at', models.DateTimeField()),
                ('user_client_update_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_admin_web',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserAdmin',
        ),
    ]
