# Generated by Django 4.2.1 on 2023-09-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_useradminweb_delete_useradmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradminweb',
            options={},
        ),
    ]
