# Generated by Django 4.2.1 on 2023-09-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_alter_useradminweb_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradminweb',
            options={},
        ),
    ]
