# Generated by Django 4.2.1 on 2023-09-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_alter_useradminweb_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradminweb',
            options={'managed': False},
        ),
    ]
