# Generated by Django 5.0.1 on 2024-01-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('document_type', models.CharField(max_length=20, verbose_name='Tipo de Documento')),
                ('document_number', models.PositiveIntegerField(verbose_name='Numero')),
                ('lastname', models.CharField(max_length=500, verbose_name='Apellidos')),
                ('name', models.CharField(max_length=500, verbose_name='Nombres')),
                ('country', models.CharField(max_length=200, verbose_name='Pais')),
                ('state_province', models.CharField(max_length=200, verbose_name='Provincia o Estado')),
                ('city', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('postal_code', models.CharField(default='S/N', max_length=200, verbose_name='Codigo Postal')),
                ('phone_number', models.CharField(default='Sin Telefono Convencional', max_length=50, verbose_name='Telefono')),
                ('cellphone_number', models.CharField(max_length=50, verbose_name='Celular')),
                ('email', models.CharField(default='No Posee email', max_length=100, verbose_name='E-mail')),
                ('client_img', models.CharField(max_length=500, verbose_name='Imagen')),
                ('employee_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, verbose_name='Codigo de Empleado')),
                ('employee_date_of_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('employee_contract_type', models.CharField(default='No posee contrato', max_length=256, verbose_name='Tipo de Contrato')),
                ('employee_contract_code', models.CharField(default='No posee codigo', max_length=256, verbose_name='Codigo de Contrato')),
                ('employee_admission_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('employee_departure_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('employee_departament', models.CharField(max_length=256, verbose_name='Area o Departamento')),
                ('employee_position', models.CharField(max_length=256, verbose_name='Cargo')),
                ('employee_extension_number', models.CharField(default='No Posee Extensión', max_length=50, verbose_name='Numero de Extensión')),
                ('employee_status', models.CharField(max_length=50, verbose_name='Estado')),
                ('employee_status_description', models.CharField(default='Ninguna', max_length=256, verbose_name='Descripción')),
                ('employee_create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('employee_upgrade_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'EMPLEADO',
                'verbose_name_plural': 'EMPLEADOS',
                'db_table': 'APIS_EMPLOYEE',
            },
        ),
    ]
