# Generated by Django 4.2 on 2024-01-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevelModel',
            fields=[
                ('user_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_level_name', models.CharField(max_length=256, verbose_name='Nombre del Nivel')),
                ('user_level_status', models.CharField(max_length=50, verbose_name='Estado')),
                ('user_level_status_description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descripción')),
                ('user_level_create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('user_level_update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'NIVEL DE USUARIO',
                'verbose_name_plural': 'NIVELES DE USUARIO',
                'db_table': 'USER_LEVEL',
            },
        ),
        migrations.CreateModel(
            name='UserEmployeeModel',
            fields=[
                ('user_employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_employee_user_name', models.CharField(max_length=256, verbose_name='Nombre de Usuario')),
                ('user_employee_password', models.CharField(max_length=16, verbose_name='Contraseña')),
                ('user_employee_login', models.BooleanField(verbose_name='Logueado')),
                ('user_employee_status', models.CharField(max_length=50, verbose_name='Estado')),
                ('user_employee_status_description', models.CharField(default='Ninguna', max_length=256, verbose_name='Descripción')),
                ('user_employee_create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('user_employee_update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('fk_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeemodel')),
                ('fk_user_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userlevelmodel')),
            ],
            options={
                'verbose_name': 'USURIO DE EMPLEADO',
                'verbose_name_plural': 'USUARIOS DE EMPLEADO',
                'db_table': 'USER_EMPLOYEE',
            },
        ),
        migrations.CreateModel(
            name='UserClientModel',
            fields=[
                ('user_client_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_client_user_name', models.CharField(max_length=256, verbose_name='Nombre de Usuario')),
                ('user_client_password', models.CharField(max_length=16, verbose_name='Contraseña')),
                ('user_client_login', models.BooleanField(verbose_name='Logueado')),
                ('user_client_status', models.CharField(max_length=50, verbose_name='Estado')),
                ('user_client_status_description', models.CharField(default='Ninguna', max_length=256, verbose_name='Descripción')),
                ('user_client_create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('user_client_update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('fk_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientmodel')),
            ],
            options={
                'verbose_name': 'USUARIO DEL CLIENTE',
                'verbose_name_plural': 'USUARIOS DEL CLIENTE',
                'db_table': 'USER_CLIENT',
            },
        ),
    ]
