# Generated by Django 4.2 on 2024-01-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userclientmodel',
            table='APIS_USER_CLIENT',
        ),
        migrations.AlterModelTable(
            name='useremployeemodel',
            table='APIS_USER_EMPLOYEE',
        ),
        migrations.AlterModelTable(
            name='userlevelmodel',
            table='APIS_USER_LEVEL',
        ),
    ]
