# Generated by Django 4.2 on 2024-01-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userclientmodel_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployeemodel',
            name='user_employee_user_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre de Usuario'),
        ),
    ]
