# Generated by Django 5.0.2 on 2024-03-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteDetailModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'DETALLE DE NOTA DE CREDITO',
                'verbose_name_plural': 'DETALLE DE NOTAS DE CREDITO',
                'db_table': 'APIS_CREDIT_NOTE_DETAIL',
            },
        ),
        migrations.CreateModel(
            name='CreditNoteModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=100, verbose_name='Numero de Comprobante')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('total', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'NOTA DE CREDITO',
                'verbose_name_plural': 'NOTAS DE CREDITO',
                'db_table': 'APIS_CREDIT_NOTE',
            },
        ),
        migrations.CreateModel(
            name='SaleDetailModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'DETALLE DE FACTURA',
                'verbose_name_plural': 'DETALLE DE FACTURAS',
                'db_table': 'APIS_SALE_DETAIL',
            },
        ),
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.CharField(max_length=50, verbose_name='Numero de establecimiento')),
                ('sale_billing_number', models.CharField(max_length=50, verbose_name='Numero de Libretin')),
                ('voucher_number', models.CharField(max_length=100, verbose_name='Numero de Comprobante')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'FACTURA',
                'verbose_name_plural': 'FACTURAS',
                'db_table': 'APIS_SALE',
            },
        ),
        migrations.CreateModel(
            name='VoucherTypeModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de Comprobante')),
                ('description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'TIPO DE COMPROBANTE',
                'verbose_name_plural': 'TIPOS DE COMPROBANTE',
                'db_table': 'APIS_VOUCHER_TYPE',
            },
        ),
        migrations.CreateModel(
            name='WayToPayModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Forma de Pago')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'FORMA DE PAGO',
                'verbose_name_plural': 'FORMAS DE PAGO',
                'db_table': 'APIS_WAY_TO_PAY',
            },
        ),
    ]
