# Generated by Django 5.0.1 on 2024-02-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteDetailModel',
            fields=[
                ('credit_note_detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_detail_quantity', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Cantidad')),
                ('credit_note_detail_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'DETALLE DE NOTA DE CREDITO',
                'verbose_name_plural': 'DETALLE DE NOTAS DE CREDITO',
                'db_table': 'APIS_CREDIT_NOTE_DETAIL',
            },
        ),
        migrations.CreateModel(
            name='CreditNoteModel',
            fields=[
                ('credit_note_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_voucher_number', models.CharField(max_length=100, verbose_name='Numero de Comprobante')),
                ('credit_note_date', models.DateField(verbose_name='Fecha')),
                ('credit_note_total', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Total')),
                ('credit_note_status', models.CharField(max_length=50, verbose_name='Estado')),
                ('credit_note_description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descripción')),
                ('credit_note_create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'NOTA DE CREDITO',
                'verbose_name_plural': 'NOTAS DE CREDITO',
                'db_table': 'APIS_CREDIT_NOTE',
            },
        ),
        migrations.CreateModel(
            name='SaleDetailModel',
            fields=[
                ('sale_detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_detail_quantity', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Cantidad')),
                ('sale_detail_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'DETALLE DE FACTURA',
                'verbose_name_plural': 'DETALLE DE FACTURAS',
                'db_table': 'APIS_SALE_DETAIL',
            },
        ),
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_establishment', models.CharField(max_length=50, verbose_name='Numero de establecimiento')),
                ('sale_billing_number', models.CharField(max_length=50, verbose_name='Numero de Libretin')),
                ('sale_voucher_number', models.CharField(max_length=100, verbose_name='Numero de Comprobante')),
                ('sale_date', models.DateField(verbose_name='Fecha')),
                ('sale_tax', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='IVA')),
                ('sale_total', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total')),
                ('sale_status', models.CharField(max_length=50, verbose_name='Estado')),
                ('sale_status_description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descripción')),
                ('sale_create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'FACTURA',
                'verbose_name_plural': 'FACTURAS',
                'db_table': 'APIS_SALE',
            },
        ),
        migrations.CreateModel(
            name='VoucherTypeModel',
            fields=[
                ('voucher_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type_name', models.CharField(max_length=100, verbose_name='Tipo de Comprobante')),
                ('voucher_type_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción')),
                ('voucher_type_create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('voucher_type_update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'TIPO DE COMPROBANTE',
                'verbose_name_plural': 'TIPOS DE COMPROBANTE',
                'db_table': 'APIS_VOUCHER_TYPE',
            },
        ),
        migrations.CreateModel(
            name='WayToPayModel',
            fields=[
                ('way_to_pay_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('way_to_pay_name', models.CharField(max_length=100, verbose_name='Forma de Pago')),
                ('way_to_pay_description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descripcion')),
                ('way_to_pay_create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('way_to_pay_update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'FORMA DE PAGO',
                'verbose_name_plural': 'FORMAS DE PAGO',
                'db_table': 'APIS_WAY_TO_PAY',
            },
        ),
    ]
