# Generated by Django 5.0.2 on 2024-02-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotemodel',
            name='credit_note_status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='sale_status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vouchertypemodel',
            name='voucher_type_status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
