# Generated by Django 5.0.2 on 2024-04-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotemodel',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total'),
        ),
    ]
