# Generated by Django 5.0.2 on 2024-03-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotemodel',
            name='credit_note_update_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='creditnotemodel',
            name='credit_note_description',
            field=models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='vouchertypemodel',
            name='voucher_type_status_description',
            field=models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='waytopaymodel',
            name='way_to_pay_status_description',
            field=models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado'),
        ),
    ]
