# Generated by Django 4.2 on 2024-01-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientcheckmodel',
            table='APIS_CLIENT_CHECK',
        ),
        migrations.AlterModelTable(
            name='clientmodel',
            table='APIS_CLIENT',
        ),
    ]
