# Generated by Django 5.0.2 on 2024-04-08 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmployeeModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='Nombre de Usuario')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('login', models.BooleanField(blank=True, default=False, null=True, verbose_name='Logueado')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('fk_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeemodel', verbose_name='Empeado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'USURIO DE EMPLEADO',
                'verbose_name_plural': 'USUARIOS DE EMPLEADO',
                'db_table': 'APIS_USER_EMPLOYEE',
            },
        ),
        migrations.CreateModel(
            name='UserClientModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256, verbose_name='Nombre de Usuario')),
                ('password', models.CharField(max_length=16, verbose_name='Contraseña')),
                ('login', models.BooleanField(verbose_name='Logueado')),
                ('fk_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientmodel', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'USUARIO DEL CLIENTE',
                'verbose_name_plural': 'USUARIOS DEL CLIENTE',
                'db_table': 'APIS_USER_CLIENT',
            },
        ),
        migrations.CreateModel(
            name='UserLevelModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre del Nivel')),
                ('fk_user_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'NIVEL DE USUARIO',
                'verbose_name_plural': 'NIVELES DE USUARIO',
                'db_table': 'APIS_USER_LEVEL',
            },
        ),
        migrations.AddField(
            model_name='useremployeemodel',
            name='fk_user_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userlevelmodel', verbose_name='Nivel'),
        ),
    ]
