# Generated by Django 5.0.2 on 2024-02-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployeemodel',
            name='user_employee_login',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Logueado'),
        ),
    ]
