# Generated by Django 5.0.2 on 2024-03-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useremployeemodel_user_employee_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployeemodel',
            name='user_employee_status',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
