# Generated by Django 4.2.7 on 2023-11-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nationality', models.CharField(max_length=30, verbose_name='Nacionalidad')),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
