# Generated by Django 5.0.1 on 2024-01-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('credit_note_id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_note_voucher_number', models.CharField(max_length=100)),
                ('credit_note_date', models.DateField()),
                ('credit_note_total', models.DecimalField(decimal_places=0, max_digits=11)),
                ('credit_note_status', models.IntegerField()),
                ('credit_note_description', models.CharField(blank=True, max_length=256, null=True)),
                ('credit_note_create_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'NOTA DE CREDITO',
                'verbose_name_plural': 'NOTAS DE CREDITO',
                'db_table': 'CREDIT_NOTE',
            },
        ),
        migrations.CreateModel(
            name='CreditNoteDetail',
            fields=[
                ('credit_note_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_note_detail_quantity', models.DecimalField(decimal_places=2, max_digits=11)),
                ('credit_note_detail_price', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
            options={
                'verbose_name': 'DETALLE DE NOTA DE CREDITO',
                'verbose_name_plural': 'DETALLE DE NOTAS DE CREDITO',
                'db_table': 'CREDIT_NOTE_DETAIL',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_voucher_type', models.CharField(max_length=256)),
                ('sale_establishment', models.CharField(max_length=50)),
                ('sale_billing_number', models.CharField(max_length=50)),
                ('sale_voucher_number', models.CharField(max_length=100)),
                ('sale_date', models.DateField()),
                ('sale_tax', models.DecimalField(decimal_places=2, max_digits=11)),
                ('sale_total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('sale_status', models.IntegerField()),
                ('sale_status_description', models.CharField(blank=True, max_length=256, null=True)),
                ('sale_create_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'FACTURA',
                'verbose_name_plural': 'FACTURAS',
                'db_table': 'SALE',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('sale_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_detail_quantity', models.DecimalField(decimal_places=2, max_digits=11)),
                ('sale_detail_price', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
            options={
                'verbose_name': 'DETALLE DE FACTURA',
                'verbose_name_plural': 'DETALLE DE FACTURAS',
                'db_table': 'SALE_DETAIL',
            },
        ),
        migrations.CreateModel(
            name='WayToPay',
            fields=[
                ('way_to_pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('way_to_pay_name', models.CharField(max_length=100)),
                ('way_to_pay_description', models.CharField(blank=True, max_length=256, null=True)),
                ('way_to_pay_create_at', models.DateTimeField()),
                ('way_to_pay_update_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FORMA DE PAGO',
                'verbose_name_plural': 'FORMAS DE PAGO',
                'db_table': 'WAY_TO_PAY',
            },
        ),
    ]
