# Generated by Django 5.0.1 on 2024-01-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waytopay',
            name='way_to_pay_create_at',
            field=models.DateTimeField(verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='waytopay',
            name='way_to_pay_description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='waytopay',
            name='way_to_pay_name',
            field=models.CharField(max_length=100, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='waytopay',
            name='way_to_pay_update_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización'),
        ),
    ]
